"""
api.routers.explain
===================
Router for the POST /explain/shap endpoint.

Receives SHAP values from a prediction and returns a natural-language
explanation (PT-BR) generated by Gemini via Vertex AI.

Environment variables
---------------------
GOOGLE_CLOUD_PROJECT : str
    GCP project ID.
GOOGLE_CLOUD_LOCATION : str
    Vertex AI region (e.g. ``us-central1``).
GEMINI_MODEL : str
    Gemini model ID (e.g. ``gemini-2.5-flash``).
"""

from __future__ import annotations

import os

from fastapi import APIRouter, HTTPException, status

from api.schemas import ExplanationResponse, ShapExplanationRequest

router = APIRouter(prefix="/explain", tags=["explainability"])

# Human-readable PT-BR labels used inside the LLM prompt.
_FEATURE_LABELS: dict[str, str] = {
    "origin_wx_precipitation": "precipitação na origem",
    "destination_wx_precipitation": "precipitação no destino",
    "total_hourly_congestion": "congestionamento total na hora",
    "airline_hour_delay_rate": "taxa histórica de atraso da companhia neste horário",
    "origin_elevation_ft": "altitude do aeroporto de origem",
    "origin_wx_windspeed_10m": "velocidade do vento na origem",
    "route_hist_delay_rate": "taxa histórica de atraso da rota",
    "destination_wx_windspeed_10m": "velocidade do vento no destino",
    "dep_dow_cos": "dia da semana da partida",
    "dep_month_cos": "mês da partida",
    "origin_wx_cloudcover": "cobertura de nuvens na origem",
    "origin_region": "região do aeroporto de origem",
    "destination_wx_cloudcover": "cobertura de nuvens no destino",
    "origin_hourly_flights": "número de voos na hora na origem",
    "origin_wx_temperature_2m": "temperatura na origem",
    "destination_wx_temperature_2m": "temperatura no destino",
    "origin_wx_windgusts_10m": "rajadas de vento na origem",
    "destination_wx_windgusts_10m": "rajadas de vento no destino",
    "origin_wx_surface_pressure": "pressão atmosférica na origem",
    "destination_wx_surface_pressure": "pressão atmosférica no destino",
    "origin_wx_condition": "condição meteorológica na origem",
    "destination_wx_condition": "condição meteorológica no destino",
    "dep_hour_sin": "horário de partida",
    "dep_hour_cos": "horário de partida",
    "dep_dow_sin": "dia da semana da partida",
    "dep_month_sin": "mês da partida",
    "dep_time_block": "bloco de horário da partida",
    "dep_is_peak_hour": "horário de pico",
    "dep_is_weekend": "final de semana",
    "dep_is_holiday": "feriado",
    "dep_day_of_year": "dia do ano",
    "route": "rota",
    "region_pair": "par de regiões",
    "distance_km": "distância da rota",
    "flight_range": "classificação da rota por distância",
    "elevation_diff_ft": "diferença de altitude entre os aeroportos",
    "origin_airport_size": "porte do aeroporto de origem",
    "destination_airport_size": "porte do aeroporto de destino",
    "is_trunk_route": "rota troncal",
    "scheduled_duration_min": "duração programada do voo",
    "destination_hourly_arrivals": "chegadas na hora no destino",
    "route_hist_delay_mean": "média histórica de atraso da rota",
    "route_hist_delay_std": "desvio padrão histórico de atraso da rota",
    "airline_hour_delay_mean": "média histórica de atraso da companhia neste horário",
}

_TOP_N = 5


def _build_prompt(payload: ShapExplanationRequest) -> str:
    """
    Build a PT-BR prompt for the LLM from SHAP values and optional flight context.

    Parameters
    ----------
    payload : ShapExplanationRequest
        Request body containing SHAP values and optional flight metadata.

    Returns
    -------
    str
        Formatted prompt ready to be sent to the generative model.
    """
    shap = payload.shap_explanation
    sorted_features = sorted(shap.values.items(), key=lambda x: abs(x[1]), reverse=True)
    top = sorted_features[:_TOP_N]

    lines = []
    for feat, val in top:
        label = _FEATURE_LABELS.get(feat, feat.replace("_", " "))
        direction = "aumenta" if val > 0 else "reduz"
        lines.append(
            f"- {label}: {direction} a probabilidade de atraso (contribuição: {val:+.4f})"
        )

    features_block = "\n".join(lines)

    context_parts = []
    if payload.airline_icao:
        context_parts.append(f"Companhia aérea: {payload.airline_icao}")
    if payload.origin_icao and payload.destination_icao:
        context_parts.append(
            f"Rota: {payload.origin_icao} → {payload.destination_icao}"
        )
    if payload.delay_proba is not None:
        context_parts.append(
            f"Probabilidade de atraso prevista: {payload.delay_proba:.1%}"
        )

    context_block = (
        "\n".join(context_parts)
        if context_parts
        else "Nenhum contexto adicional fornecido."
    )

    return f"""
        Você é um assistente especialista em aviação civil brasileira.
        Analise os resultados de um modelo de machine learning que prevê atrasos em voos domésticos.

        Contexto do voo:
        {context_block}

        Os fatores que mais influenciaram a previsão (valores SHAP — positivo aumenta a chance de atraso, negativo reduz):
        {features_block}

        Probabilidade base do modelo (média histórica): {shap.base_value:.1%}

        Escreva uma explicação clara e objetiva em português do Brasil, em 3 a 5 frases, voltada para um usuário final
        (não técnico). Explique os principais fatores que contribuíram para a previsão sem usar jargões de machine learning.
        Não mencione "SHAP", "features" ou termos técnicos do modelo.
    """


def _call_vertex_gemini(prompt: str) -> str:
    """
    Send a prompt to Gemini via Vertex AI and return the response text.

    Parameters
    ----------
    prompt : str
        Fully formatted prompt string.

    Returns
    -------
    str
        Raw text from the model response.

    Raises
    ------
    RuntimeError
        If ``GOOGLE_CLOUD_PROJECT`` is not set.
    """
    from google import genai

    project = os.environ.get("GOOGLE_CLOUD_PROJECT")
    location = os.environ.get("GOOGLE_CLOUD_LOCATION", "us-central1")
    model_id = os.environ.get("GEMINI_MODEL", "gemini-2.0-flash")

    if not project:
        raise RuntimeError("GOOGLE_CLOUD_PROJECT environment variable is not set.")

    client = genai.Client(vertexai=True, project=project, location=location)
    response = client.models.generate_content(model=model_id, contents=prompt)
    return response.text


@router.post(
    "/shap",
    response_model=ExplanationResponse,
    summary="Generate a natural-language explanation from SHAP values",
    description="""
        Receives SHAP values from a prediction and returns a **PT-BR** natural-language
        explanation generated by Gemini (Vertex AI) about the main factors that
        influenced the delay forecast.

        Optionally accepts flight context (`airline_icao`, `origin_icao`,
        `destination_icao`, `delay_proba`) to enrich the explanation.

        **Required environment variables:** `GOOGLE_CLOUD_PROJECT`, `GOOGLE_CLOUD_LOCATION`, `GEMINI_MODEL`.
    """,
)
def explain_shap(payload: ShapExplanationRequest) -> ExplanationResponse:
    """
    Generate a PT-BR explanation for a delay prediction using SHAP values.

    Parameters
    ----------
    payload : ShapExplanationRequest
        SHAP explanation data plus optional flight context.

    Returns
    -------
    ExplanationResponse
        Natural-language explanation produced by the LLM.
    """
    if not payload.shap_explanation.values:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail="shap_explanation.values cannot be empty.",
        )

    prompt = _build_prompt(payload)

    try:
        text = _call_vertex_gemini(prompt)
    except RuntimeError as exc:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=str(exc),
        )
    except Exception as exc:
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail=f"Vertex AI error: {exc}",
        )

    return ExplanationResponse(explanation=text.strip())
